_target_: src.datamodules.Triplet_SHREC13_datamodule_2.SHREC13_DataModule_2
data_dir: ${paths.data_dir}
# batch_size: 4
batch_size: 30
num_workers: 0
pin_memory: False
nb_points: 2048
dset_norm: 2
w2v_path: ${paths.w2v_path}
